name: Auto Deploy Builds Page

on:
  push:
    branches:
      - main
  
  
jobs:
  build:

    name: Auto Deploy Builds Page
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      EMAIL: ${{ secrets.EMAIL }}
      ACTION_NAME: ${GITHUB_WORKFLOW}
      RUN_ID: ${GITHUB_RUN_NUMBER}

    steps:
    
    - name: Checking out Repository
      uses: actions/checkout@v3
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '16.x'
          
    - name: Installing node dependencies      
      run: npm install
      
    - name: Running builder
      run: npm run deploy
