name: Auto Deploy Maven

on:
  # Manual workflow trigger
  workflow_dispatch:
  # On workflow call or dispatch
  workflow_call:

# env context
env:
    API_KEY: ${{ secrets.API_KEY }}
    EMAIL: ${{ secrets.EMAIL }}
    ACTION_NAME: ${GITHUB_WORKFLOW}
    RUN_ID: ${GITHUB_RUN_NUMBER}
  
jobs:
  # job name
  build:
    # runner
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Repository
        uses: actions/checkout@v3

      - name: Setting up Java 17
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'adopt'
          java-version: '17'
          java-package: jdk
          architecture: x64        

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
            node-version: '16.x'

      - name: Installing node dependencies      
        run: npm install

      - name: Running maven builder and committer
        run: npm start
